MythAPI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mythosAPI.urls')),
    path('entities/', include('entity.urls')),
]

entity/urls.py
from django.urls import path, include
from rest_framework import routers
from .api import EntityViewSet
from django.conf.urls.static import static
from django.conf import settings

from . import views

router = routers.DefaultRouter()
router.register('api', EntityViewSet, 'api')

urlpatterns = [
    path('list', views.list, name='list'),
    path('<int:entityID>', views.single, name='entity'),
    path('api/<name>', EntityViewSet.as_view({'get': 'retrieve'})),
    path('api/<entityID>', EntityViewSet.as_view({'get': 'retrieve'})),
    path('api/<origin>', EntityViewSet.as_view({'get': 'filter'})),
    path('', include(router.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mythosAPI/urls.py
from mythosAPI.views import documentation
from django.views.decorators.csrf import csrf_exempt
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('documentation', views.documentation, name='documentation'),
    # path('email', csrf_exempt(views.post), name="email"),

]

entity/models.py
from django.db import models

# Create your models here.

class Entity(models.Model):

  # class roleOptions(models.TextChoices):
  #   GOD = 'GD', _('God')
  #   DEMON = 'DM', _('Demon')
  #   HERO = 'HR', _('Hero')
  #   MONSTER = 'MN', _('Monster')
  
  # class originOptions(models.TextChoices):
  #   GREEK = 'GK', _('Greek')
  #   JAPANESE = 'JP', _('Japanese')
  #   SLAVIC = 'SV', _('Slavic')
  #   NORSE = 'NR', _('Norse')
  
  roleOptions = (
    ('GD', 'God'),
    ('DM', 'Demon'),
    ('HR', 'Hero'),
    ('MN', 'Monster'),
  )

  originOptions = (
    ('GK', 'Greek'),
    ('JP', 'Japanese'),
    ('SV', 'Slavic'),
    ('NR', 'Norse'),
  )
  
  entityID = models.AutoField(primary_key=True)
  name = models.CharField(max_length=20)
  title = models.CharField(max_length=50)
  description = models.CharField(max_length=200)
  parents = models.CharField(max_length=20) 
  origin = models.CharField(max_length=2, choices=originOptions)
  role = models.CharField(max_length=2, choices=roleOptions)
  greatest_Feats = models.CharField(max_length=200)
  image = models.ImageField(upload_to='photos/%Y/%m/%d/')

  def __str__(self):
    return self.name

  class Meta:
    ordering = ("origin","name")

mythosAPI/models.py
from django.db import models

# Create your models here.

mythosAPI/forms.py
from django import forms

class emailForm(forms.Form):
    subject = forms.CharField(label='Name of Entity', max_length=100)
    message = forms.CharField(label='Description   ', max_length=500)

entity/views.py
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Entity
# Create your views here.
def index(request):

	return render(request, 'entities/entity.html')

def list(request):
	entity = Entity.objects.all()

	context = {
		'entities': entity
	}
	return render(request, 'entities/entities.html', context)

def single(request, entityID):
	entity = get_object_or_404(Entity, pk=entityID)

	context = {
		'entity': entity
	}

	return render(request, 'entities/entity.html', context)

mythosAPI/views.py
from django.shortcuts import render
from django.template import RequestContext
from .forms import emailForm
from django.core.mail import send_mail
from entity.models import Entity


# Create your views here.
##url request 
def index(request): 
  if request.method == 'POST':
    form = emailForm(request.POST)
    if form.is_valid():
      subject = form.cleaned_data['subject']  
      message = form.cleaned_data['message']  
      send_mail(subject, message, 'mythosAPI@gmail.com', ['parmjit.singh.1199@gmail.com'], fail_silently=False)
    else:
      form = emailForm()

  
  return render(request, 'mythosAPI_Pages/index.html', {'form': emailForm()})
  # data = [{'Name': 'Prometheus', 'Description': 'Titan', 'Origin': 'Greek','Role': 'Hero', 'Traits': 'Regeneration', 'Greatest Feats': 'Giving fire to humans', 'Image': 'path/to/image.jpg'}]
  # return JsonResponse(data, safe=False)
  # return HttpResponse('<h1>First Response in Django</h1>')

def about(request):
  return render(request, 'mythosAPI_Pages/about.html')

def documentation(request):
  return render(request, 'mythosAPI_Pages/documentation.html')

def post(request):
  form = request.POST.get("subject")
  print(form)
  return render(request, 'mythosAPI_Pages/index.html')

templates/base.html
{% load  static %}
<!DOCTYPE html>
<html lang='en'>
<head>
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <title> Mythos API </title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel='stylesheet' type='text/css' media='screen' href="{% static 'main.css' %}">
  <script src="https://kit.fontawesome.com/25a02deeaf.js" crossorigin="anonymous"></script>
</head>
<div class="wrapper">
  <div class="sidebar">
    <a href="/">
      <img class="logo" src="{% static 'logo/poseidon.png' %}">
    </a>
    <h2 class="header"> Mythos API </h2>

    <ul>
      <li><a href="/documentation"><i class="fas fa-book"></i> Documentation </a></li>
      <li><a href="/entities/list"><i class="fas fa-th-list"></i> List </a></li>
      <li><a href="/about"><i class="fas fa-info"></i> About </a></li>
    </ul>
    <div class="social_media">
      <a href="https://twitter.com/_Parmjit_" target="_blank"><i class="fab fa-twitter"></i></a>
      <a href="https://github.com/Wolf-PSG?tab=repositories" target="_blank"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fas fa-donate" target="_blank"></i></a>

    </div>
  </div>
  <div class="main_content">

    <body>
      {% block content %}

      {% endblock %}
    </body>
  </div>

  <div class="footer">
  </div>
</div>

</html>

templates/entities/entities.html
{% extends 'base.html' %}
{% load static %}
{% block content  %}

<head>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'main.css' %}">

</head>
<section class="entities">
  <div class="container">
    <h1>Entity List</h1>
    {% if entities %}
    {% for entity in entities  %}
    <a href="/entities/{{entity.entityID}}">
      <div class="entity_container">
        <img class="entity_img" src="{{static|add:entity.image.url}}" />
        <h2 class="entity_name"> {{ entity.name }} </h2>
        <h5 class="entity_origin"> {{ entity.get_origin_display }}</h5>
        <h5 class="entity_title"> {{ entity.title }} </h5>
      </div>
    </a>
    {% endfor %}
    {% else %}
    <div class="none">
      <h2> No Entities found - something went wrong </h2>
    </div>
    {% endif %}
  </div>
</section>
{% endblock  %}

templates/entities/entity.html
{% extends 'base.html' %}
{% load static %}
{% block content  %}


<head>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
      <link rel='stylesheet' type='text/css' media='screen' href="{% static 'main.css' %}">

</head>
<section class="entity">
    <div class="container">
        <h1>{{entity.name}}</h1>
        {% if entity %}
        <div class="entity_container">
            <img class="entity_img" src="{{entity.image.url}}" />
            <p> {{entity.description}}</p>
            <p> {{entity.parents}}
        </div>
        {% else %}
        <div class="none">
            <h2> No Entity found - something went wrong </h2>
        </div>
        {% endif %}
    </div>
</section>
{% endblock  %}

templates/mythosAPI_Pages/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
      <link rel='stylesheet' type='text/css' media='screen' href="{% static 'main.css' %}">

</head>
<div class="wrapper-content">
    <h1> About MythosAPI </h1>

    <body>
        <div class="body-para"> I always had a fancination for mythical creatures and deities of different cultures <br>
            so
            for my portfolio
            I created This API! <br> This API was built in Django using the rest framework. I really enjoyed this
            language
            and project. <br>
            If you like this API feel free to follow me on social media for any updates on this and future projects <br>
            And if really like this API feel free to donate - I will add your name to the list of donators on here. <br>
        </div>
        <div>Icons made by <a href="https://www.flaticon.com/authors/those-icons" title="Those Icons">Those
                Icons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
    </body>
</div>

{% endblock %}

templates/mythosAPI_Pages/documentation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'main.css' %}">

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.3.1/styles/atom-one-light.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.3.1/highlight.min.js"></script>
<script>
        hljs.initHighlightingOnLoad();
    </script>
</head>
<div class="container_documentation">
    <div class="wrapper_getAll">
        <h1> Documentation </h1>
        <p class="brief"> How to use the Mythos API - examples using Jquery </p>
        <h2> Get all Entities </h2>
        <div>
            <pre><code class="markdown"> https://mythosapi.herokuapp.com/entities/api</code></pre>
        </div>
        <div class="desc_getAll">
            <div>
                <h3> Jquery </h3>
                <pre><code class="javascript">
            $.ajax({
                url: "https://mythosapi.herokuapp.com/entities/api/",
                type: 'get',
                success: function (data) {
                    alert("do something")
                }
            })
        </code></pre>
            </div>
            <div class="JSON_res">
                <h3> JSON: </h3>
                <pre class="JSON_block"><code class="json" id="json-1"></code></pre>
                <script>
                    $.ajax({
                        url: "https://mythosapi.herokuapp.com/entities/api/",
                        type: 'get',
                        success: function (data) {
                            var div = document.getElementById('json-1');
                            div.innerHTML = div.innerHTML + JSON.stringify(data, null, " ");
                            hljs.highlightBlock(document.getElementById('json-1'))
                        }
                    });
                </script>
            </div>
        </div>
    </div>

    <div class="wrapper_getSingle">
        <h2> Get Single Entity </h2>
        <div>
            <pre><code class="markdown"> https://mythosapi.herokuapp.com/entities/api/2/name-of-entity || entityID </code></pre>
        </div>
        <div class="desc_getSingle">
            The names are case sensitive <br>
        </div>
        <div>
            <h3> Jquery </h3>
            <pre><code class="javascript">
            $.ajax({
                url: "https://mythosapi.herokuapp.com/entities/api/Zeus",
                type: 'get',
                success: function (data) {
                    alert("do something")
                }
            })
        </code></pre>
        </div>
        <div class="JSON_res">
            <h3> JSON: </h3>
            <div class="JSON_block">
                <pre><code class="json" id="json-2"></code></pre>
            </div>
            <script>
                $.ajax({
                    url: "https://mythosapi.herokuapp.com/entities/api/Zeus",
                    type: 'get',
                    success: function (data) {
                        var div = document.getElementById('json-2');
                        div.innerHTML = div.innerHTML + JSON.stringify(data, null, " ");
                        hljs.highlightBlock(document.getElementById('json-2'))
                    }
                });
            </script>
        </div>
    </div>
</div>
{% endblock %}

templates/mythosAPI_Pages/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<div class="wrapper-content">
    <h1 class="heading_1"> Welcome </h1>
    <div class="container_body">

        <body> Welcome to the Mythos API. The one place where you can find data on mythical creatures and entities from
            myths, legends and folklore </body>
    </div>

    <section class="section_form">
        <h1 class="heading_2"> Have a creature you would like to add? </h1>
        <h4 class="subheading_1"> write the name of your entity and a brief idea of who they <br>
            I can research them and add them into the database!</h4>
        <form id="form_email" action="/" method="post">
            <div class="form_container">
                {% csrf_token %}
                {{form}}
                <input class="submitEntity_btn" type="submit"></input>
            </div>
        </form>

    </section>
</div>
{% endblock %}